package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbClasse generated by hbm2java
 */
@Entity
@Table(name = "tb_classe", schema = "public")
public class Classe implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descricao;
	private Set<Ordem> ordems = new HashSet<Ordem>(0);

	public Classe() {
	}

	public Classe(int idtbClasse) {
		this.id = idtbClasse;
	}

	public Classe(int idtbClasse, String descricao, Set<Ordem> ordems) {
		this.id = idtbClasse;
		this.descricao = descricao;
		this.ordems = ordems;
	}

	@Id
	@Column(name = "idtb_classe", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", length = 75)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbClasse")
	public Set<Ordem> getTbOrdems() {
		return this.ordems;
	}

	public void setTbOrdems(Set<Ordem> ordems) {
		this.ordems = ordems;
	}

}
