package br.ufs.coleta.SISColeta.entities;

// Generated Jul 24, 2015 11:11:15 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbColetor generated by hbm2java
 */
@Entity
@Table(name = "tb_coletor", schema = "public")
public class Coletor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ColetorId id;
	private Coleta coleta;
	private Usuario usuario;
	private Boolean determinador;

	public Coletor() {
	}

	public Coletor(ColetorId id, Coleta coleta, Usuario usuario) {
		this.id = id;
		this.coleta = coleta;
		this.usuario = usuario;
	}

	public Coletor(ColetorId id, Coleta coleta, Usuario usuario,
			Boolean determinador) {
		this.id = id;
		this.coleta = coleta;
		this.usuario = usuario;
		this.determinador = determinador;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "coletaId", column = @Column(name = "tb_coleta_id", nullable = false)),
			@AttributeOverride(name = "usuarioId", column = @Column(name = "tb_usuario_id", nullable = false)) })
	public ColetorId getId() {
		return this.id;
	}

	public void setId(ColetorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_coleta_id", nullable = false, insertable = false, updatable = false)
	public Coleta getColeta() {
		return this.coleta;
	}

	public void setColeta(Coleta coleta) {
		this.coleta = coleta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_usuario_id", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "determinador")
	public Boolean getDeterminador() {
		return this.determinador;
	}

	public void setDeterminador(Boolean determinador) {
		this.determinador = determinador;
	}

}
