package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

/**
 * TbColecao generated by hbm2java
 */
@Entity
@Table(name = "tb_colecao", schema = "public")
@NamedQueries({
	@NamedQuery(name="Colecao.findByColeta", query="SELECT c FROM Colecao c WHERE c.tbColeta.id = :idcoleta"),
	@NamedQuery(name="Colecao.findByEspecie", query="SELECT c FROM Colecao c INNER JOIN c.tbEspecie e WHERE UPPER(e.nomeCientifico) LIKE :nome OR UPPER(e.nomePopular) LIKE :nome "),
	@NamedQuery(name="Colecao.getColeta", query="SELECT c FROM Coleta c INNER JOIN c.tbColecaos co WHERE co.id = :id "),	
})
public class Colecao implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Coleta coleta;
	private Especie especie;
	private Usuario usuario;
	private Usuario determinador;
	private Destino destino;
	private Unidade unidade;
	private Integer quantidade;
	private String codCampo;
	private Set<RetiradaColecao> retiradaColecaos = new HashSet<RetiradaColecao>(
			0);
	private Set<ColecaoImagem> colecaoImagems = new HashSet<ColecaoImagem>(
			0);

	public Colecao() {
	}

	public Colecao(Integer idtbColecao, Coleta coleta, Especie especie,
			Usuario usuario, Destino destino, Unidade unidade) {
		this.id = idtbColecao;
		this.coleta = coleta;
		this.especie = especie;
		this.usuario = usuario;
		this.destino = destino;
		this.unidade = unidade;
	}

	public Colecao(Integer idtbColecao, Coleta coleta, Especie especie,
			Usuario usuario, Integer quantidade, Unidade unidade,
			Destino destino,
			Set<RetiradaColecao> retiradaColecaos,
			Set<ColecaoImagem> colecaoImagems) {
		this.id = idtbColecao;
		this.coleta = coleta;
		this.especie = especie;
		this.usuario = usuario;
		this.quantidade = quantidade;
		this.unidade = unidade;
		this.destino = destino;
		this.retiradaColecaos = retiradaColecaos;
		this.colecaoImagems = colecaoImagems;
	}

	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id
	@Column(name = "idtb_colecao", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_coleta_id", nullable = false)
	public Coleta getTbColeta() {
		return this.coleta;
	}

	public void setTbColeta(Coleta coleta) {
		this.coleta = coleta;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tb_especie_id", nullable = false)
	@NotNull(message = "Campo não pode ser vázio!")
	public Especie getTbEspecie() {
		return this.especie;
	}

	public void setTbEspecie(Especie especie) {
		this.especie = especie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_usuario_id", nullable = false)
	public Usuario getTbUsuario() {
		return this.usuario;
	}

	public void setTbUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_determinador", nullable = false)
	public Usuario getDeterminador() {
		return this.determinador;
	}

	public void setDeterminador(Usuario determinador) {
		this.determinador = determinador;
	}

	@Column(name = "quantidade")
	@NotNull(message = "Campo não pode ser vázio!")
	@Pattern(regexp = "[\\s]*[0-9]*[1-9]+",message="Campo deve ser um número positivo")
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}	

	@Column(name = "cod_campo", length = 20)
	@NotNull(message = "Campo não pode ser vázio!")
	public String getCodCampo() {
		return codCampo;
	}

	public void setCodCampo(String codCampo) {
		this.codCampo = codCampo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tb_unidade_id", nullable = false)
	@NotNull(message = "Campo não pode ser vázio!")
	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tb_destino_id", nullable = false)
	public Destino getDestino() {
		return this.destino;
	}

	public void setDestino(Destino destino) {
		this.destino = destino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbColecao")
	public Set<RetiradaColecao> getTbRetiradaColecaos() {
		return this.retiradaColecaos;
	}

	public void setTbRetiradaColecaos(Set<RetiradaColecao> retiradaColecaos) {
		this.retiradaColecaos = retiradaColecaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbColecao")
	public Set<ColecaoImagem> getTbColecaoImagems() {
		return this.colecaoImagems;
	}

	public void setTbColecaoImagems(Set<ColecaoImagem> colecaoImagems) {
		this.colecaoImagems = colecaoImagems;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Colecao)) {
            return false;
        }
        Colecao other = (Colecao) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
