package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbColecaoImagem generated by hbm2java
 */
@Entity
@Table(name = "tb_colecao_imagem", schema = "public")
public class ColecaoImagem implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Colecao colecao;
	private String imagem;

	public ColecaoImagem() {
	}

	public ColecaoImagem(int idtbColecaoImagem, Colecao colecao) {
		this.id = idtbColecaoImagem;
		this.colecao = colecao;
	}

	public ColecaoImagem(int idtbColecaoImagem, Colecao colecao,
			String imagem) {
		this.id = idtbColecaoImagem;
		this.colecao = colecao;
		this.imagem = imagem;
	}

	@Id
	@Column(name = "idtb_colecao_imagem", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_colecao_id", nullable = false)
	public Colecao getTbColecao() {
		return this.colecao;
	}

	public void setTbColecao(Colecao colecao) {
		this.colecao = colecao;
	}

	@Column(name = "imagem")
	public String getImagem() {
		return this.imagem;
	}

	public void setImagem(String imagem) {
		this.imagem = imagem;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof ColecaoImagem)) {
            return false;
        }
        ColecaoImagem other = (ColecaoImagem) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
