package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbEspecie generated by hbm2java
 */
@Entity
@Table(name = "tb_especie", schema = "public")
public class Especie implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Subfamilia subfamilia;
	private String nomeCientifico;
	private String nomePopular;
	private Set<EspecieImagem> especieImagems = new HashSet<EspecieImagem>(
			0);
	private Set<Colecao> colecaos = new HashSet<Colecao>(0);

	public Especie() {
	}

	public Especie(int idtbEspecie, Subfamilia subfamilia) {
		this.id = idtbEspecie;
		this.subfamilia = subfamilia;
	}

	public Especie(int idtbEspecie, Subfamilia subfamilia,
			String nomeCientifico, String nomePopular,
			Set<EspecieImagem> especieImagems, Set<Colecao> colecaos) {
		this.id = idtbEspecie;
		this.subfamilia = subfamilia;
		this.nomeCientifico = nomeCientifico;
		this.nomePopular = nomePopular;
		this.especieImagems = especieImagems;
		this.colecaos = colecaos;
	}

	@Id
	@Column(name = "idtb_especie", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_subfamilia_id", nullable = false)
	public Subfamilia getTbSubfamilia() {
		return this.subfamilia;
	}

	public void setTbSubfamilia(Subfamilia subfamilia) {
		this.subfamilia = subfamilia;
	}

	@Column(name = "nome_cientifico", length = 75)
	public String getNomeCientifico() {
		return this.nomeCientifico;
	}

	public void setNomeCientifico(String nomeCientifico) {
		this.nomeCientifico = nomeCientifico;
	}

	@Column(name = "nome_popular", length = 75)
	public String getNomePopular() {
		return this.nomePopular;
	}

	public void setNomePopular(String nomePopular) {
		this.nomePopular = nomePopular;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEspecie")
	public Set<EspecieImagem> getTbEspecieImagems() {
		return this.especieImagems;
	}

	public void setTbEspecieImagems(Set<EspecieImagem> especieImagems) {
		this.especieImagems = especieImagems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEspecie")
	public Set<Colecao> getTbColecaos() {
		return this.colecaos;
	}

	public void setTbColecaos(Set<Colecao> colecaos) {
		this.colecaos = colecaos;
	}

}
