package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbFamilia generated by hbm2java
 */
@Entity
@Table(name = "tb_familia", schema = "public")
public class Familia implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Ordem ordem;
	private String descricao;
	private Set<Subfamilia> subfamilias = new HashSet<Subfamilia>(0);

	public Familia() {
	}

	public Familia(int idtbFamilia, Ordem ordem) {
		this.id = idtbFamilia;
		this.ordem = ordem;
	}

	public Familia(int idtbFamilia, Ordem ordem, String descricao,
			Set<Subfamilia> subfamilias) {
		this.id = idtbFamilia;
		this.ordem = ordem;
		this.descricao = descricao;
		this.subfamilias = subfamilias;
	}

	@Id
	@Column(name = "idtb_familia", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_ordem_id", nullable = false)
	public Ordem getTbOrdem() {
		return this.ordem;
	}

	public void setTbOrdem(Ordem ordem) {
		this.ordem = ordem;
	}

	@Column(name = "descricao", length = 75)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbFamilia")
	public Set<Subfamilia> getTbSubfamilias() {
		return this.subfamilias;
	}

	public void setTbSubfamilias(Set<Subfamilia> subfamilias) {
		this.subfamilias = subfamilias;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Familia)) {
            return false;
        }
        Familia other = (Familia) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
