package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbMunicipio generated by hbm2java
 */
@Entity
@Table(name = "tb_municipio", schema = "public")
@NamedQueries({
	@NamedQuery(name="Municipio.findByMunicipio", query="SELECT m FROM Municipio m WHERE m.tbEstado.id = :id"),
})
public class Municipio implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Estado estado;
	private String nome;
	private Set<Coleta> coletas = new HashSet<Coleta>(0);
	private Set<Instituicao> instituicaos = new HashSet<Instituicao>(0);

	public Municipio() {
	}

	public Municipio(int idtbMunicipio, Estado estado) {
		this.id = idtbMunicipio;
		this.estado = estado;
	}

	public Municipio(int idtbMunicipio, Estado estado, String nome,
			Set<Coleta> coletas, Set<Instituicao> instituicaos) {
		this.id = idtbMunicipio;
		this.estado = estado;
		this.nome = nome;
		this.coletas = coletas;
		this.instituicaos = instituicaos;
	}

	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id
	@Column(name = "idtb_municipio", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tb_estado_id", nullable = false)
	public Estado getTbEstado() {
		return this.estado;
	}

	public void setTbEstado(Estado estado) {
		this.estado = estado;
	}

	@Column(name = "nome", length = 75)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbMunicipio")
	public Set<Coleta> getTbColetas() {
		return this.coletas;
	}

	public void setTbColetas(Set<Coleta> coletas) {
		this.coletas = coletas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbMunicipio")
	public Set<Instituicao> getTbInstituicaos() {
		return this.instituicaos;
	}

	public void setTbInstituicaos(Set<Instituicao> instituicaos) {
		this.instituicaos = instituicaos;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Municipio)) {
            return false;
        }
        Municipio other = (Municipio) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
