package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbOceano generated by hbm2java
 */
@Entity
@Table(name = "tb_oceano", schema = "public")
public class Oceano implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descricao;
	private Set<Mar> mars = new HashSet<Mar>(0);

	public Oceano() {
	}

	public Oceano(int idtbOceano) {
		this.id = idtbOceano;
	}

	public Oceano(int idtbOceano, String descricao, Set<Mar> mars) {
		this.id = idtbOceano;
		this.descricao = descricao;
		this.mars = mars;
	}

	@Id
	@Column(name = "idtb_oceano", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", length = 75)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbOceano")
	public Set<Mar> getTbMars() {
		return this.mars;
	}

	public void setTbMars(Set<Mar> mars) {
		this.mars = mars;
	}

}
