package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbRetirada generated by hbm2java
 */
@Entity
@Table(name = "tb_retirada", schema = "public")
@NamedQueries({
	@NamedQuery(name="Retirada.findByColecao", query="SELECT r FROM RetiradaColecao r JOIN r.tbColecao rc JOIN r.tbRetirada rt WHERE rt.id = :id"),
})
public class Retirada implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Destinatario destinatario;
	private String modoEnvio;
	private Integer numeroPacote;
	private Integer tipoRetirada;
	private Set<RetiradaColecao> retiradaColecaos = new HashSet<RetiradaColecao>(
			0);

	public Retirada() {
	}

	public Retirada(int idtbRetirada, Destinatario destinatario) {
		this.id = idtbRetirada;
		this.destinatario = destinatario;
	}

	public Retirada(int idtbRetirada, Destinatario destinatario,
			String modoEnvio, Integer numeroPacote, Integer tipoRetirada,
			Set<RetiradaColecao> retiradaColecaos) {
		this.id = idtbRetirada;
		this.destinatario = destinatario;
		this.modoEnvio = modoEnvio;
		this.numeroPacote = numeroPacote;
		this.tipoRetirada = tipoRetirada;
		this.retiradaColecaos = retiradaColecaos;
	}

	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id
	@Column(name = "idtb_retirada", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tb_destinatario_id", nullable = false)
	public Destinatario getTbDestinatario() {
		return this.destinatario;
	}

	public void setTbDestinatario(Destinatario destinatario) {
		this.destinatario = destinatario;
	}

	@Column(name = "modo_envio", length = 45)
	public String getModoEnvio() {
		return this.modoEnvio;
	}

	public void setModoEnvio(String modoEnvio) {
		this.modoEnvio = modoEnvio;
	}

	@Column(name = "numero_pacote")
	public Integer getNumeroPacote() {
		return this.numeroPacote;
	}

	public void setNumeroPacote(Integer numeroPacote) {
		this.numeroPacote = numeroPacote;
	}

	@Column(name = "tipo_retirada")
	public Integer getTipoRetirada() {
		return this.tipoRetirada;
	}

	public void setTipoRetirada(Integer tipoRetirada) {
		this.tipoRetirada = tipoRetirada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbRetirada")
	public Set<RetiradaColecao> getTbRetiradaColecaos() {
		return this.retiradaColecaos;
	}

	public void setTbRetiradaColecaos(Set<RetiradaColecao> retiradaColecaos) {
		this.retiradaColecaos = retiradaColecaos;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Retirada)) {
            return false;
        }
        Retirada other = (Retirada) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
