package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbRio generated by hbm2java
 */
@Entity
@Table(name = "tb_rio", schema = "public")
public class Rio implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Bacia bacia;
	private String descricao;
	private Set<Aquatico> aquaticos = new HashSet<Aquatico>(0);

	public Rio() {
	}

	public Rio(int idtbRio, Bacia bacia) {
		this.id = idtbRio;
		this.bacia = bacia;
	}

	public Rio(int idtbRio, Bacia bacia, String descricao,
			Set<Aquatico> aquaticos) {
		this.id = idtbRio;
		this.bacia = bacia;
		this.descricao = descricao;
		this.aquaticos = aquaticos;
	}

	@Id
	@Column(name = "idtb_rio", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_bacia_id", nullable = false)
	public Bacia getTbBacia() {
		return this.bacia;
	}

	public void setTbBacia(Bacia bacia) {
		this.bacia = bacia;
	}

	@Column(name = "descricao", length = 75)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbMar")
	public Set<Aquatico> getTbAquaticos() {
		return this.aquaticos;
	}

	public void setTbAquaticos(Set<Aquatico> aquaticos) {
		this.aquaticos = aquaticos;
	}

}
