package br.ufs.coleta.SISColeta.entities;

// Generated 25/01/2015 11:00:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbSubfamilia generated by hbm2java
 */
@Entity
@Table(name = "tb_subfamilia", schema = "public")
public class Subfamilia implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Familia familia;
	private String descricao;
	private Set<Especie> especies = new HashSet<Especie>(0);

	public Subfamilia() {
	}

	public Subfamilia(int idtbSubfamilia, Familia familia) {
		this.id = idtbSubfamilia;
		this.familia = familia;
	}

	public Subfamilia(int idtbSubfamilia, Familia familia,
			String descricao, Set<Especie> especies) {
		this.id = idtbSubfamilia;
		this.familia = familia;
		this.descricao = descricao;
		this.especies = especies;
	}

	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id
	@Column(name = "idtb_subfamilia", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tb_familia_id", nullable = false)
	public Familia getTbFamilia() {
		return this.familia;
	}

	public void setTbFamilia(Familia familia) {
		this.familia = familia;
	}

	@Column(name = "descricao", length = 75)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbSubfamilia")
	public Set<Especie> getTbEspecies() {
		return this.especies;
	}

	public void setTbEspecies(Set<Especie> especies) {
		this.especies = especies;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Subfamilia)) {
            return false;
        }
        Subfamilia other = (Subfamilia) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
