package br.ufs.coleta.SISColeta.entities;

// Generated Jul 29, 2015 1:49:01 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbSubstratosId generated by hbm2java
 */
@Embeddable
public class SubstratosId implements java.io.Serializable {

	private int tbSubstratoId;
	private int tbColetaId;

	public SubstratosId() {
	}

	public SubstratosId(int tbSubstratoId, int tbColetaId) {
		this.tbSubstratoId = tbSubstratoId;
		this.tbColetaId = tbColetaId;
	}

	@Column(name = "tb_substrato_id", nullable = false)
	public int getTbSubstratoId() {
		return this.tbSubstratoId;
	}

	public void setTbSubstratoId(int tbSubstratoId) {
		this.tbSubstratoId = tbSubstratoId;
	}

	@Column(name = "tb_coleta_id", nullable = false)
	public int getTbColetaId() {
		return this.tbColetaId;
	}

	public void setTbColetaId(int tbColetaId) {
		this.tbColetaId = tbColetaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubstratosId))
			return false;
		SubstratosId castOther = (SubstratosId) other;

		return (this.getTbSubstratoId() == castOther.getTbSubstratoId())
				&& (this.getTbColetaId() == castOther.getTbColetaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTbSubstratoId();
		result = 37 * result + this.getTbColetaId();
		return result;
	}

}
