package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbColecaoImagem generated by hbm2java
 */
@Entity
@Table(name = "tb_colecao_imagem", schema = "public")
public class TbColecaoImagem implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private TbColecao tbColecao;
	private String imagem;

	public TbColecaoImagem() {
	}

	public TbColecaoImagem(int idtbColecaoImagem, TbColecao tbColecao) {
		this.id = idtbColecaoImagem;
		this.tbColecao = tbColecao;
	}

	public TbColecaoImagem(int idtbColecaoImagem, TbColecao tbColecao,
			String imagem) {
		this.id = idtbColecaoImagem;
		this.tbColecao = tbColecao;
		this.imagem = imagem;
	}

	@Id
	@Column(name = "idtb_colecao_imagem", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_colecao_id", nullable = false)
	public TbColecao getTbColecao() {
		return this.tbColecao;
	}

	public void setTbColecao(TbColecao tbColecao) {
		this.tbColecao = tbColecao;
	}

	@Column(name = "imagem")
	public String getImagem() {
		return this.imagem;
	}

	public void setImagem(String imagem) {
		this.imagem = imagem;
	}

}
