package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbColeta generated by hbm2java
 */
@Entity
@Table(name = "tb_coleta", schema = "public")
public class TbColeta implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private TbMunicipio tbMunicipio;
	private TbHabitat tbHabitat;
	private TbMetodoColeta tbMetodoColeta;
	private String datum;
	private Date dataInicio;
	private Date dataFim;
	private Set<TbColecao> tbColecaos = new HashSet<TbColecao>(0);
	private Set<TbUsuario> tbUsuarios = new HashSet<TbUsuario>(0);

	public TbColeta() {
	}

	public TbColeta(int idtbColeta, TbMunicipio tbMunicipio,
			TbHabitat tbHabitat, TbMetodoColeta tbMetodoColeta) {
		this.id = idtbColeta;
		this.tbMunicipio = tbMunicipio;
		this.tbHabitat = tbHabitat;
		this.tbMetodoColeta = tbMetodoColeta;
	}

	public TbColeta(int idtbColeta, TbMunicipio tbMunicipio,
			TbHabitat tbHabitat, TbMetodoColeta tbMetodoColeta, String datum,
			Date dataInicio, Date dataFim, Set<TbColecao> tbColecaos,
			Set<TbUsuario> tbUsuarios) {
		this.id = idtbColeta;
		this.tbMunicipio = tbMunicipio;
		this.tbHabitat = tbHabitat;
		this.tbMetodoColeta = tbMetodoColeta;
		this.datum = datum;
		this.dataInicio = dataInicio;
		this.dataFim = dataFim;
		this.tbColecaos = tbColecaos;
		this.tbUsuarios = tbUsuarios;
	}

	@Id
	@Column(name = "idtb_coleta", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_municipio_id", nullable = false)
	public TbMunicipio getTbMunicipio() {
		return this.tbMunicipio;
	}

	public void setTbMunicipio(TbMunicipio tbMunicipio) {
		this.tbMunicipio = tbMunicipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_habitat_id", nullable = false)
	public TbHabitat getTbHabitat() {
		return this.tbHabitat;
	}

	public void setTbHabitat(TbHabitat tbHabitat) {
		this.tbHabitat = tbHabitat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_metodo_coleta_id", nullable = false)
	public TbMetodoColeta getTbMetodoColeta() {
		return this.tbMetodoColeta;
	}

	public void setTbMetodoColeta(TbMetodoColeta tbMetodoColeta) {
		this.tbMetodoColeta = tbMetodoColeta;
	}

	@Column(name = "datum", length = 20)
	public String getDatum() {
		return this.datum;
	}

	public void setDatum(String datum) {
		this.datum = datum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inicio", length = 29)
	public Date getDataInicio() {
		return this.dataInicio;
	}

	public void setDataInicio(Date dataInicio) {
		this.dataInicio = dataInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_fim", length = 29)
	public Date getDataFim() {
		return this.dataFim;
	}

	public void setDataFim(Date dataFim) {
		this.dataFim = dataFim;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbColeta")
	public Set<TbColecao> getTbColecaos() {
		return this.tbColecaos;
	}

	public void setTbColecaos(Set<TbColecao> tbColecaos) {
		this.tbColecaos = tbColecaos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tb_coletor", schema = "public", joinColumns = { @JoinColumn(name = "tb_coleta_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "tb_usuario_id", nullable = false, updatable = false) })
	public Set<TbUsuario> getTbUsuarios() {
		return this.tbUsuarios;
	}

	public void setTbUsuarios(Set<TbUsuario> tbUsuarios) {
		this.tbUsuarios = tbUsuarios;
	}

}
