package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbEstado generated by hbm2java
 */
@Entity
@Table(name = "tb_estado", schema = "public")
public class TbEstado implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String descricao;
	private Set<TbMunicipio> tbMunicipios = new HashSet<TbMunicipio>(0);

	public TbEstado() {
	}

	public TbEstado(int idtbEstado) {
		this.id = idtbEstado;
	}

	public TbEstado(int idtbEstado, String descricao,
			Set<TbMunicipio> tbMunicipios) {
		this.id = idtbEstado;
		this.descricao = descricao;
		this.tbMunicipios = tbMunicipios;
	}

	@Id
	@Column(name = "idtb_estado", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEstado")
	public Set<TbMunicipio> getTbMunicipios() {
		return this.tbMunicipios;
	}

	public void setTbMunicipios(Set<TbMunicipio> tbMunicipios) {
		this.tbMunicipios = tbMunicipios;
	}

}
