package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbEspecie generated by hbm2java
 */
@Entity
@Table(name = "tb_especie", schema = "public")
public class TbEspecie implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private TbOrdem tbOrdem;
	private TbReino tbReino;
	private TbGenero tbGenero;
	private TbFamilia tbFamilia;
	private String nome;
	private Set<TbEspecieImagem> tbEspecieImagems = new HashSet<TbEspecieImagem>(
			0);
	private Set<TbColecao> tbColecaos = new HashSet<TbColecao>(0);

	public TbEspecie() {
	}

	public TbEspecie(int idtbEspecie, TbOrdem tbOrdem, TbReino tbReino,
			TbGenero tbGenero, TbFamilia tbFamilia) {
		this.id = idtbEspecie;
		this.tbOrdem = tbOrdem;
		this.tbReino = tbReino;
		this.tbGenero = tbGenero;
		this.tbFamilia = tbFamilia;
	}

	public TbEspecie(int idtbEspecie, TbOrdem tbOrdem, TbReino tbReino,
			TbGenero tbGenero, TbFamilia tbFamilia, String nome,
			Set<TbEspecieImagem> tbEspecieImagems, Set<TbColecao> tbColecaos) {
		this.id = idtbEspecie;
		this.tbOrdem = tbOrdem;
		this.tbReino = tbReino;
		this.tbGenero = tbGenero;
		this.tbFamilia = tbFamilia;
		this.nome = nome;
		this.tbEspecieImagems = tbEspecieImagems;
		this.tbColecaos = tbColecaos;
	}

	@Id
	@Column(name = "idtb_especie", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_ordem_id", nullable = false)
	public TbOrdem getTbOrdem() {
		return this.tbOrdem;
	}

	public void setTbOrdem(TbOrdem tbOrdem) {
		this.tbOrdem = tbOrdem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_reino_id", nullable = false)
	public TbReino getTbReino() {
		return this.tbReino;
	}

	public void setTbReino(TbReino tbReino) {
		this.tbReino = tbReino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_genero_id", nullable = false)
	public TbGenero getTbGenero() {
		return this.tbGenero;
	}

	public void setTbGenero(TbGenero tbGenero) {
		this.tbGenero = tbGenero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_familia_id", nullable = false)
	public TbFamilia getTbFamilia() {
		return this.tbFamilia;
	}

	public void setTbFamilia(TbFamilia tbFamilia) {
		this.tbFamilia = tbFamilia;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEspecie")
	public Set<TbEspecieImagem> getTbEspecieImagems() {
		return this.tbEspecieImagems;
	}

	public void setTbEspecieImagems(Set<TbEspecieImagem> tbEspecieImagems) {
		this.tbEspecieImagems = tbEspecieImagems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbEspecie")
	public Set<TbColecao> getTbColecaos() {
		return this.tbColecaos;
	}

	public void setTbColecaos(Set<TbColecao> tbColecaos) {
		this.tbColecaos = tbColecaos;
	}

}
