package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbEspecieImagem generated by hbm2java
 */
@Entity
@Table(name = "tb_especie_imagem", schema = "public")
public class TbEspecieImagem implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private TbEspecie tbEspecie;
	private String imagem;

	public TbEspecieImagem() {
	}

	public TbEspecieImagem(int idtbEspecieImagem, TbEspecie tbEspecie) {
		this.id = idtbEspecieImagem;
		this.tbEspecie = tbEspecie;
	}

	public TbEspecieImagem(int idtbEspecieImagem, TbEspecie tbEspecie,
			String imagem) {
		this.id = idtbEspecieImagem;
		this.tbEspecie = tbEspecie;
		this.imagem = imagem;
	}

	@Id
	@Column(name = "idtb_especie_imagem", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_especie_id", nullable = false)
	public TbEspecie getTbEspecie() {
		return this.tbEspecie;
	}

	public void setTbEspecie(TbEspecie tbEspecie) {
		this.tbEspecie = tbEspecie;
	}

	@Column(name = "imagem")
	public String getImagem() {
		return this.imagem;
	}

	public void setImagem(String imagem) {
		this.imagem = imagem;
	}

}
