package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbHabitat generated by hbm2java
 */
@Entity
@Table(name = "tb_habitat", schema = "public")
public class TbHabitat implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private TbAquatico tbAquatico;
	private Double latitude;
	private Character direcaoLatitude;
	private Double longitude;
	private Character direcaoLongitude;
	private Set<TbColeta> tbColetas = new HashSet<TbColeta>(0);

	public TbHabitat() {
	}

	public TbHabitat(int idtbHabitat, TbAquatico tbAquatico) {
		this.id = idtbHabitat;
		this.tbAquatico = tbAquatico;
	}

	public TbHabitat(int idtbHabitat, TbAquatico tbAquatico, Double latitude,
			Character direcaoLatitude, Double longitude,
			Character direcaoLongitude, Set<TbColeta> tbColetas) {
		this.id = idtbHabitat;
		this.tbAquatico = tbAquatico;
		this.latitude = latitude;
		this.direcaoLatitude = direcaoLatitude;
		this.longitude = longitude;
		this.direcaoLongitude = direcaoLongitude;
		this.tbColetas = tbColetas;
	}

	@Id
	@Column(name = "idtb_habitat", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_aquatico_id", nullable = false)
	public TbAquatico getTbAquatico() {
		return this.tbAquatico;
	}

	public void setTbAquatico(TbAquatico tbAquatico) {
		this.tbAquatico = tbAquatico;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "direcao_latitude", length = 1)
	public Character getDirecaoLatitude() {
		return this.direcaoLatitude;
	}

	public void setDirecaoLatitude(Character direcaoLatitude) {
		this.direcaoLatitude = direcaoLatitude;
	}

	@Column(name = "longitude", precision = 17, scale = 17)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "direcao_longitude", length = 1)
	public Character getDirecaoLongitude() {
		return this.direcaoLongitude;
	}

	public void setDirecaoLongitude(Character direcaoLongitude) {
		this.direcaoLongitude = direcaoLongitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbHabitat")
	public Set<TbColeta> getTbColetas() {
		return this.tbColetas;
	}

	public void setTbColetas(Set<TbColeta> tbColetas) {
		this.tbColetas = tbColetas;
	}

}
