package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbInstituicao generated by hbm2java
 */
@Entity
@Table(name = "tb_instituicao", schema = "public")
public class TbInstituicao implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private TbMunicipio tbMunicipio;
	private String nome;
	private String endereco;
	private String bairro;
	private String cep;
	private Set<TbDestinatario> tbDestinatarios = new HashSet<TbDestinatario>(0);

	public TbInstituicao() {
	}

	public TbInstituicao(int idtbInstituicao, TbMunicipio tbMunicipio) {
		this.id = idtbInstituicao;
		this.tbMunicipio = tbMunicipio;
	}

	public TbInstituicao(int idtbInstituicao, TbMunicipio tbMunicipio,
			String nome, String endereco, String bairro, String cep,
			Set<TbDestinatario> tbDestinatarios) {
		this.id = idtbInstituicao;
		this.tbMunicipio = tbMunicipio;
		this.nome = nome;
		this.endereco = endereco;
		this.bairro = bairro;
		this.cep = cep;
		this.tbDestinatarios = tbDestinatarios;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idtb_instituicao", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_municipio_id", nullable = false)
	public TbMunicipio getTbMunicipio() {
		return this.tbMunicipio;
	}

	public void setTbMunicipio(TbMunicipio tbMunicipio) {
		this.tbMunicipio = tbMunicipio;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "endereco", length = 75)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "bairro", length = 45)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cep", length = 20)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbInstituicao")
	public Set<TbDestinatario> getTbDestinatarios() {
		return this.tbDestinatarios;
	}

	public void setTbDestinatarios(Set<TbDestinatario> tbDestinatarios) {
		this.tbDestinatarios = tbDestinatarios;
	}

}
