package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbMar generated by hbm2java
 */
@Entity
@Table(name = "tb_mar", schema = "public")
public class TbMar implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TbOceano tbOceano;
	private String descricao;
	private Set<TbAquatico> tbAquaticos = new HashSet<TbAquatico>(0);

	public TbMar() {
	}

	public TbMar(int idtbMar, TbOceano tbOceano) {
		this.id = idtbMar;
		this.tbOceano = tbOceano;
	}

	public TbMar(int idtbMar, TbOceano tbOceano, String descricao,
			Set<TbAquatico> tbAquaticos) {
		this.id = idtbMar;
		this.tbOceano = tbOceano;
		this.descricao = descricao;
		this.tbAquaticos = tbAquaticos;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idtb_mar", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tb_oceano_id", referencedColumnName = "idtb_oceano", nullable = false)
	public TbOceano getTbOceano() {
		return this.tbOceano;
	}

	public void setTbOceano(TbOceano tbOceano) {
		this.tbOceano = tbOceano;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbMar")
	public Set<TbAquatico> getTbAquaticos() {
		return this.tbAquaticos;
	}

	public void setTbAquaticos(Set<TbAquatico> tbAquaticos) {
		this.tbAquaticos = tbAquaticos;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof TbMar)) {
            return false;
        }
        TbMar other = (TbMar) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
