package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbMetodoColeta generated by hbm2java
 */
@Entity
@Table(name = "tb_metodo_coleta", schema = "public")
public class TbMetodoColeta implements GenericEntity {

	private static final long serialVersionUID = 1L;
	private int id;
	private String descricao;
	private Set<TbColeta> tbColetas = new HashSet<TbColeta>(0);

	public TbMetodoColeta() {
	}

	public TbMetodoColeta(int idtbMetodoColeta) {
		this.id = idtbMetodoColeta;
	}

	public TbMetodoColeta(int idtbMetodoColeta, String descricao,
			Set<TbColeta> tbColetas) {
		this.id = idtbMetodoColeta;
		this.descricao = descricao;
		this.tbColetas = tbColetas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idtb_metodo_coleta", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbMetodoColeta")
	public Set<TbColeta> getTbColetas() {
		return this.tbColetas;
	}

	public void setTbColetas(Set<TbColeta> tbColetas) {
		this.tbColetas = tbColetas;
	}

}
