package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbMunicipio generated by hbm2java
 */
@Entity
@Table(name = "tb_municipio", schema = "public")
public class TbMunicipio implements java.io.Serializable {

	private int idtbMunicipio;
	private TbEstado tbEstado;
	private String descricao;
	private Set<TbColeta> tbColetas = new HashSet<TbColeta>(0);
	private Set<TbInstituicao> tbInstituicaos = new HashSet<TbInstituicao>(0);

	public TbMunicipio() {
	}

	public TbMunicipio(int idtbMunicipio, TbEstado tbEstado) {
		this.idtbMunicipio = idtbMunicipio;
		this.tbEstado = tbEstado;
	}

	public TbMunicipio(int idtbMunicipio, TbEstado tbEstado, String descricao,
			Set<TbColeta> tbColetas, Set<TbInstituicao> tbInstituicaos) {
		this.idtbMunicipio = idtbMunicipio;
		this.tbEstado = tbEstado;
		this.descricao = descricao;
		this.tbColetas = tbColetas;
		this.tbInstituicaos = tbInstituicaos;
	}

	@Id
	@Column(name = "idtb_municipio", unique = true, nullable = false)
	public int getIdtbMunicipio() {
		return this.idtbMunicipio;
	}

	public void setIdtbMunicipio(int idtbMunicipio) {
		this.idtbMunicipio = idtbMunicipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_estado_id", nullable = false)
	public TbEstado getTbEstado() {
		return this.tbEstado;
	}

	public void setTbEstado(TbEstado tbEstado) {
		this.tbEstado = tbEstado;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbMunicipio")
	public Set<TbColeta> getTbColetas() {
		return this.tbColetas;
	}

	public void setTbColetas(Set<TbColeta> tbColetas) {
		this.tbColetas = tbColetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbMunicipio")
	public Set<TbInstituicao> getTbInstituicaos() {
		return this.tbInstituicaos;
	}

	public void setTbInstituicaos(Set<TbInstituicao> tbInstituicaos) {
		this.tbInstituicaos = tbInstituicaos;
	}

}
