package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbMunicipio generated by hbm2java
 */
@Entity
@Table(name = "tb_municipio", schema = "public")
@NamedQueries({
    @NamedQuery(name = "Municipio.findAll", query = "SELECT m FROM TbMunicipio m"),
    @NamedQuery(name = "Municipio.findByIdEstado", query = "SELECT m FROM TbMunicipio m WHERE m.tbEstado.id = :id"),})
public class TbMunicipio implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TbEstado tbEstado;
	private String descricao;
	private Set<TbColeta> tbColetas = new HashSet<TbColeta>(0);
	private Set<TbInstituicao> tbInstituicaos = new HashSet<TbInstituicao>(0);

	public TbMunicipio() {
	}

	public TbMunicipio(int idtbMunicipio, TbEstado tbEstado) {
		this.id = idtbMunicipio;
		this.tbEstado = tbEstado;
	}
	
	public TbMunicipio(int idtbMunicipio, TbEstado tbEstado, String descricao,
			Set<TbColeta> tbColetas, Set<TbInstituicao> tbInstituicaos) {
		this.id = idtbMunicipio;
		this.tbEstado = tbEstado;
		this.descricao = descricao;
		this.tbColetas = tbColetas;
		this.tbInstituicaos = tbInstituicaos;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idtb_municipio", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tb_estado_id", referencedColumnName = "idtb_estado", nullable = false)
	public TbEstado getTbEstado() {
		return this.tbEstado;
	}

	public void setTbEstado(TbEstado tbEstado) {
		this.tbEstado = tbEstado;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(mappedBy = "tbMunicipio")
	public Set<TbColeta> getTbColetas() {
		return this.tbColetas;
	}

	public void setTbColetas(Set<TbColeta> tbColetas) {
		this.tbColetas = tbColetas;
	}

	@OneToMany(mappedBy = "tbMunicipio")
	public Set<TbInstituicao> getTbInstituicaos() {
		return this.tbInstituicaos;
	}

	public void setTbInstituicaos(Set<TbInstituicao> tbInstituicaos) {
		this.tbInstituicaos = tbInstituicaos;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof TbMunicipio)) {
            return false;
        }
        TbMunicipio other = (TbMunicipio) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
