package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbOceano generated by hbm2java
 */
@Entity
@Table(name = "tb_oceano", schema = "public")
public class TbOceano implements java.io.Serializable {

	private int idtbOceano;
	private String descricao;
	private Set<TbMar> tbMars = new HashSet<TbMar>(0);

	public TbOceano() {
	}

	public TbOceano(int idtbOceano) {
		this.idtbOceano = idtbOceano;
	}

	public TbOceano(int idtbOceano, String descricao, Set<TbMar> tbMars) {
		this.idtbOceano = idtbOceano;
		this.descricao = descricao;
		this.tbMars = tbMars;
	}

	@Id
	@Column(name = "idtb_oceano", unique = true, nullable = false)
	public int getIdtbOceano() {
		return this.idtbOceano;
	}

	public void setIdtbOceano(int idtbOceano) {
		this.idtbOceano = idtbOceano;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbOceano")
	public Set<TbMar> getTbMars() {
		return this.tbMars;
	}

	public void setTbMars(Set<TbMar> tbMars) {
		this.tbMars = tbMars;
	}

}
