package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbOceano generated by hbm2java
 */
@Entity
@Table(name = "tb_oceano", schema = "public")
public class TbOceano implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String descricao;
	private Set<TbMar> tbMars = new HashSet<TbMar>(0);

	public TbOceano() {
	}

	public TbOceano(int idtbOceano) {
		this.id = idtbOceano;
	}

	public TbOceano(int idtbOceano, String descricao, Set<TbMar> tbMars) {
		this.id = idtbOceano;
		this.descricao = descricao;
		this.tbMars = tbMars;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idtb_oceano", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(mappedBy = "tbOceano")
	public Set<TbMar> getTbMars() {
		return this.tbMars;
	}

	public void setTbMars(Set<TbMar> tbMars) {
		this.tbMars = tbMars;
	}
	
	@Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof TbOceano)) {
            return false;
        }
        TbOceano other = (TbOceano) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}
