package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbOrdem generated by hbm2java
 */
@Entity
@Table(name = "tb_ordem", schema = "public")
public class TbOrdem implements java.io.Serializable {

	private int idtbOrdem;
	private String descricao;
	private Set<TbEspecie> tbEspecies = new HashSet<TbEspecie>(0);

	public TbOrdem() {
	}

	public TbOrdem(int idtbOrdem) {
		this.idtbOrdem = idtbOrdem;
	}

	public TbOrdem(int idtbOrdem, String descricao, Set<TbEspecie> tbEspecies) {
		this.idtbOrdem = idtbOrdem;
		this.descricao = descricao;
		this.tbEspecies = tbEspecies;
	}

	@Id
	@Column(name = "idtb_ordem", unique = true, nullable = false)
	public int getIdtbOrdem() {
		return this.idtbOrdem;
	}

	public void setIdtbOrdem(int idtbOrdem) {
		this.idtbOrdem = idtbOrdem;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbOrdem")
	public Set<TbEspecie> getTbEspecies() {
		return this.tbEspecies;
	}

	public void setTbEspecies(Set<TbEspecie> tbEspecies) {
		this.tbEspecies = tbEspecies;
	}

}
