package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbPerfil generated by hbm2java
 */
@Entity
@Table(name = "tb_perfil", schema = "public")
public class TbPerfil implements GenericEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String descricao;
	private Set<TbUsuario> tbUsuarios = new HashSet<TbUsuario>(0);

	public TbPerfil() {
	}

	public TbPerfil(int idtbPerfil) {
		this.id = idtbPerfil;
	}

	public TbPerfil(int idtbPerfil, String descricao, Set<TbUsuario> tbUsuarios) {
		this.id = idtbPerfil;
		this.descricao = descricao;
		this.tbUsuarios = tbUsuarios;
	}

	@Id
	@Column(name = "idtb_perfil", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbPerfil")
	public Set<TbUsuario> getTbUsuarios() {
		return this.tbUsuarios;
	}

	public void setTbUsuarios(Set<TbUsuario> tbUsuarios) {
		this.tbUsuarios = tbUsuarios;
	}

}
