package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbRecebimento generated by hbm2java
 */
@Entity
@Table(name = "tb_recebimento", schema = "public")
public class TbRecebimento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtbRecebimento;
	private TbRetiradaColecao tbRetiradaColecao;
	private Date dataRecebimento;
	private String observacao;

	public TbRecebimento() {
	}

	public TbRecebimento(int idtbRecebimento,
			TbRetiradaColecao tbRetiradaColecao) {
		this.idtbRecebimento = idtbRecebimento;
		this.tbRetiradaColecao = tbRetiradaColecao;
	}

	public TbRecebimento(int idtbRecebimento,
			TbRetiradaColecao tbRetiradaColecao, Date dataRecebimento,
			String observacao) {
		this.idtbRecebimento = idtbRecebimento;
		this.tbRetiradaColecao = tbRetiradaColecao;
		this.dataRecebimento = dataRecebimento;
		this.observacao = observacao;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idtb_recebimento", unique = true, nullable = false)
	public int getIdtbRecebimento() {
		return this.idtbRecebimento;
	}

	public void setIdtbRecebimento(int idtbRecebimento) {
		this.idtbRecebimento = idtbRecebimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "tb_colecao_id", referencedColumnName = "tb_colecao_id", nullable = false),
			@JoinColumn(name = "tb_retirada_id", referencedColumnName = "tb_retirada_id", nullable = false) })
	public TbRetiradaColecao getTbRetiradaColecao() {
		return this.tbRetiradaColecao;
	}

	public void setTbRetiradaColecao(TbRetiradaColecao tbRetiradaColecao) {
		this.tbRetiradaColecao = tbRetiradaColecao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_recebimento", length = 13)
	public Date getDataRecebimento() {
		return this.dataRecebimento;
	}

	public void setDataRecebimento(Date dataRecebimento) {
		this.dataRecebimento = dataRecebimento;
	}

	@Column(name = "observacao")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

}
