package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbRetirada generated by hbm2java
 */
@Entity
@Table(name = "tb_retirada", schema = "public")
public class TbRetirada implements java.io.Serializable {

	private int idtbRetirada;
	private TbDestinatario tbDestinatario;
	private String modoEnvio;
	private Integer numeroPacote;
	private Integer tipoRetirada;
	private Set<TbRetiradaColecao> tbRetiradaColecaos = new HashSet<TbRetiradaColecao>(
			0);

	public TbRetirada() {
	}

	public TbRetirada(int idtbRetirada, TbDestinatario tbDestinatario) {
		this.idtbRetirada = idtbRetirada;
		this.tbDestinatario = tbDestinatario;
	}

	public TbRetirada(int idtbRetirada, TbDestinatario tbDestinatario,
			String modoEnvio, Integer numeroPacote, Integer tipoRetirada,
			Set<TbRetiradaColecao> tbRetiradaColecaos) {
		this.idtbRetirada = idtbRetirada;
		this.tbDestinatario = tbDestinatario;
		this.modoEnvio = modoEnvio;
		this.numeroPacote = numeroPacote;
		this.tipoRetirada = tipoRetirada;
		this.tbRetiradaColecaos = tbRetiradaColecaos;
	}

	@Id
	@Column(name = "idtb_retirada", unique = true, nullable = false)
	public int getIdtbRetirada() {
		return this.idtbRetirada;
	}

	public void setIdtbRetirada(int idtbRetirada) {
		this.idtbRetirada = idtbRetirada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_destinatario_id", nullable = false)
	public TbDestinatario getTbDestinatario() {
		return this.tbDestinatario;
	}

	public void setTbDestinatario(TbDestinatario tbDestinatario) {
		this.tbDestinatario = tbDestinatario;
	}

	@Column(name = "modo_envio", length = 45)
	public String getModoEnvio() {
		return this.modoEnvio;
	}

	public void setModoEnvio(String modoEnvio) {
		this.modoEnvio = modoEnvio;
	}

	@Column(name = "numero_pacote")
	public Integer getNumeroPacote() {
		return this.numeroPacote;
	}

	public void setNumeroPacote(Integer numeroPacote) {
		this.numeroPacote = numeroPacote;
	}

	@Column(name = "tipo_retirada")
	public Integer getTipoRetirada() {
		return this.tipoRetirada;
	}

	public void setTipoRetirada(Integer tipoRetirada) {
		this.tipoRetirada = tipoRetirada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbRetirada")
	public Set<TbRetiradaColecao> getTbRetiradaColecaos() {
		return this.tbRetiradaColecaos;
	}

	public void setTbRetiradaColecaos(Set<TbRetiradaColecao> tbRetiradaColecaos) {
		this.tbRetiradaColecaos = tbRetiradaColecaos;
	}

}
