package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbRetiradaColecao generated by hbm2java
 */
@Entity
@Table(name = "tb_retirada_colecao", schema = "public")
public class TbRetiradaColecao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TbRetiradaColecaoId id;
	private TbColecao tbColecao;
	private TbRetirada tbRetirada;
	private String observacao;
	private Set<TbRecebimento> tbRecebimentos = new HashSet<TbRecebimento>(0);

	public TbRetiradaColecao() {
	}

	public TbRetiradaColecao(TbRetiradaColecaoId id, TbColecao tbColecao,
			TbRetirada tbRetirada) {
		this.id = id;
		this.tbColecao = tbColecao;
		this.tbRetirada = tbRetirada;
	}

	public TbRetiradaColecao(TbRetiradaColecaoId id, TbColecao tbColecao,
			TbRetirada tbRetirada, String observacao,
			Set<TbRecebimento> tbRecebimentos) {
		this.id = id;
		this.tbColecao = tbColecao;
		this.tbRetirada = tbRetirada;
		this.observacao = observacao;
		this.tbRecebimentos = tbRecebimentos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tbColecaoId", column = @Column(name = "tb_colecao_id", nullable = false)),
			@AttributeOverride(name = "tbRetiradaId", column = @Column(name = "tb_retirada_id", nullable = false)) })
	public TbRetiradaColecaoId getId() {
		return this.id;
	}

	public void setId(TbRetiradaColecaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_colecao_id", nullable = false, insertable = false, updatable = false)
	public TbColecao getTbColecao() {
		return this.tbColecao;
	}

	public void setTbColecao(TbColecao tbColecao) {
		this.tbColecao = tbColecao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_retirada_id", nullable = false, insertable = false, updatable = false)
	public TbRetirada getTbRetirada() {
		return this.tbRetirada;
	}

	public void setTbRetirada(TbRetirada tbRetirada) {
		this.tbRetirada = tbRetirada;
	}

	@Column(name = "observacao")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbRetiradaColecao")
	public Set<TbRecebimento> getTbRecebimentos() {
		return this.tbRecebimentos;
	}

	public void setTbRecebimentos(Set<TbRecebimento> tbRecebimentos) {
		this.tbRecebimentos = tbRecebimentos;
	}

}
