package br.ufs.coleta.SISColeta.entities;

// Generated 02/01/2015 16:46:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbReino generated by hbm2java
 */
@Entity
@Table(name = "tb_reino", schema = "public")
public class TbReino implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtbReino;
	private String descricao;
	private Set<TbEspecie> tbEspecies = new HashSet<TbEspecie>(0);

	public TbReino() {
	}

	public TbReino(int idtbReino) {
		this.idtbReino = idtbReino;
	}

	public TbReino(int idtbReino, String descricao, Set<TbEspecie> tbEspecies) {
		this.idtbReino = idtbReino;
		this.descricao = descricao;
		this.tbEspecies = tbEspecies;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "idtb_reino", unique = true, nullable = false)
	public int getIdtbReino() {
		return this.idtbReino;
	}

	public void setIdtbReino(int idtbReino) {
		this.idtbReino = idtbReino;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbReino")
	public Set<TbEspecie> getTbEspecies() {
		return this.tbEspecies;
	}

	public void setTbEspecies(Set<TbEspecie> tbEspecies) {
		this.tbEspecies = tbEspecies;
	}

}
